### ISSUE TITLE
Create A GitHub Issue

### ISSUE THREAD

**Issue by ghost** [cmneal26/Tech-Writing-Project#10]
GitHub Issues provide a convenient place to talk about the code in the repository, and organize work around that repo.

Create your first GitHub issue. For content, anything you'd like.

Assign it to Jason and Tim.

Label it as learning.

**Comment by ghost** [comment]
https://github.com/cmneal26/Tech-Writing-Project/issues/10

**Comment by ghost** [comment]
here is a comment.

**Comment by twalker** [comment]
Thanks for the label. I'm pretty used to checking most every issue 😸
