### ISSUE TITLE
Update The Content Of Your Pull Request With The Latest Changes In 'main'

### ISSUE THREAD

**Issue by ghost** [cmneal26/Tech-Writing-Project#21]
When you originally cloned your repo, you got the current version of the 'main' branch at that time. Then you created a new branch on your machine, and made some changes. Finally, you pushed those changes to GitHub. However, in-between the time when you cloned the original repo, and you opened the pull request on GitHub, Tim updated 'main' by merging in some code. 

You can see the status of the branch you want to merge into 'main' says "two commits behind": 

![branch_status](https://user-images.githubusercontent.com/32662279/175795547-c9c56e5e-f65e-4608-9621-fa3aa2be3af3.PNG)

One thing I've found helpful to avoid problems is if I always make sure the code in the branch the pull request I opened is up to date with main before merging the pull request. This isn't necessarily something you're going to be doing a lot for this course, but I think it's good to know how to do.

So, the goal of this learning issue is to update your pull request with the new content that got added to 'main' by pulling in the changes in the remote 'main' to your machine on the branch you used to open the pull request.

I'll update this ticket in a bit with some more detailed instructions for how to carry out this task.

**Comment by ghost** [comment]
Instructions For Updating Remote Repo with current 'main' content:

1. Make sure locally you're on the correct branch:
![verify_branch](https://user-images.githubusercontent.com/32662279/175796593-b3f0ed4c-e36f-49fd-9674-011ff94fb26c.PNG)

2.  Update 'my-changes' branch with 'main' content, by pulling in remote main content:
![pull_in_remote_main_changes](https://user-images.githubusercontent.com/32662279/175796601-e1cd0ede-c366-4f38-ad20-082a756d9e3b.PNG)

3.  Check repo status with 'git status':
![check_status](https://user-images.githubusercontent.com/32662279/175796631-ad9d1713-0023-44d7-8633-9215d63d2efd.PNG)

4. push the new changes to my-changes local to my-changes remote on GitHub
![push_changes_to_GitHub](https://user-images.githubusercontent.com/32662279/175796655-36f72909-742e-4d7a-b6df-e8f47ca4237d.PNG)

**Comment by cmneal26** [comment]
I see what you mean. Thanks for the instructions! I'm sure that'll be very useful in the future. For now I closed out my PR because I didn't make any changes anyway XD
