### ISSUE TITLE
Add Functionality: Retrieve Public API Data 

### ISSUE THREAD

**Issue by ghost** [cmneal26/Tech-Writing-Project#27]
## Introduction

This issue concerns implementing code to **Fetch Data At Build Time**.

There are at least two different places/times in which we could fetch live API data within the context of our Eleventy project.
- **Fetch Data At Build Time**
    - When we deploy our Eleventy app to GitHub Pages, our docs are built: we could also fetch API data at this time
- **Fetch Data In Browser**
    - When the user clicks a button, the browser fetches the API data. This happens after the Markdown content files have been converted to plain HTML files, and served to the browser to render. 

## Resources

- **[Helpful Advice](https://github.com/cmneal26/Tech-Writing-Project/issues/27#issuecomment-1168151827)**
- **For our tech education website, we want to retrieve live data via a public API. We've learned that it can be done at build time by Eleventy** - https://github.com/cmneal26/Tech-Writing-Project/issues/16
- **Use The Information in this comment as a model to update our project with functionality to retrieve data from the public API** - https://github.com/cmneal26/Tech-Writing-Project/issues/16#issuecomment-1166576151   
- **The API you should retrieve data from will be whatever the results of this issue are** - https://github.com/cmneal26/Tech-Writing-Project/issues/18
- **Example Code To Retrieve random cat facts from public api at build using Eleventy**  - https://github.com/cmneal26/Tech-Writing-Project/pull/22/files#diff-0e9a652efdbb21db89bd8edde0d8f8a681624084d4f7942bb23b8d6af0fabe40  
 
----
 
## Update

The initial plan was to use the API data fetched at build time in the tutorial for `project #1`. However, if the code I commented on that Tim has in one of his repos works, then we don't need to use it for that.

See this comment: https://github.com/cmneal26/Tech-Writing-Project/issues/27#issuecomment-1168151827

However, we still want to carry out the task of implementing the fetch-api-data-at-build functionality. Why? It represents a power of Eleventy we can now learn -- because it's likely that there will come a time in an Eleventy project (or a project in a similar environment) where we'll want talk to an api at build time.

**Comment by ghost** [comment]
@cmneal26 

Let me know if you want to setup a screen share meeting with me to carry out this task later this week (post-Wed, evening/night PDT), or if you prefer to try it on your own.

Oh, and once you decide on a cool public API, you will want to have a discussion with Tim (as the writer) about which data from the public API he thinks it makes sense to retrieve at build time from the API for use in the fetch tutorial content page. `Pending Results Of` - https://github.com/cmneal26/Tech-Writing-Project/issues/16#issuecomment-1168298873

**Comment by cmneal26** [comment]
I'm down to set up a meeting! I can also take a look at it on my own before the meeting if I have time so that we can troubleshoot anything I'm struggling with.

**Comment by ghost** [comment]
Yeah, trying it out before the meeting would be good. Go ahead and message me on the private forum with your availability, and ill update the "Next Meeting" post for us with the information. Or, if you prefer, just reply to that thread, and ill use the information from there to update the main post.

**Comment by ghost** [comment]
I thought of a few things that might be helpful, if you get around to trying it out on your own before our meeting:

- **You need to install one package to enable running the ```eleventy-fetch``` code in your new ```*.js``` file inside of ```_data```. Run ```npm install @11ty/eleventy-fetch``` from the project root directory. ([installation docs](https://www.11ty.dev/docs/plugins/fetch/#installation))**
- **After (1) installing the new dependency, (2) build the Eleventy application locally, (3) verify that the data was fetched from the public api at build time.**   
- **You only have to add one `*.js` file in the ```_data``` directory to complete this enhancement task**  
- **For now, only commit that one `*.js` file which fetches your API data**
- **Feel free to push that new local branch with your committed changes to GitHub, open a pull request, and request a code review from Tim**

If you get to that point, we should probably answer the question, "Do I commit the ```package.json``` and ```package-lock.json``` files" (add them to PR) ?

Feel free to bring this question up with Tim as a PR comment

**Comment by ghost** [comment]
- https://github.com/cmneal26/Tech-Writing-Project/pull/38
