### ISSUE TITLE
Sprint 3: Project Brainstorming

### ISSUE THREAD

**Issue by ghost** [cmneal26/Tech-Writing-Project#39]
I figured it couldn't hurt on some planning for the next project. Feel free to use this Issue to add ideas.

@cmneal26 

Would you like to be the writer for the second project or the third? I'm fine either way.

If you'd like to be the writer for the second project, is there some theme/topic that you would want to focus on? The content is totally up to you. Once we have an idea what you want to do, we can set about making more specific plans. But no hurry, just keep it in the back of your mind, and we can talk about it at our next meeting.

**Comment by ghost** [comment]
- idea 1

      - Call some environmental data api, and then a short talk or demonstration or whatever you want with the data.
      - If you would like to call data, and then graph it, let me know. I can look into some options for graphing.
      - For example, we retrieve some environmental data from an api. We already did at build, so maybe we'll add fetch in browser functionality for this project. And then we use something like a line graph to display it. You could then talk about the graph, or the graph and getting the data from the api together.

**Comment by ghost** [comment]
@cmneal26 

I moved this one to the third sprint. That should give us to time to come up with the content for this educational module.

We can consider the "Snakes and Mongooses" game as our second project, for the second sprint.

**Comment by cmneal26** [comment]
@ingrey1 

Sounds good to me! I'm fine with my project being on the third leg in you'd like to do yours next. 

For my project, I think calling data and graphing it is a great idea. I want to work the the EPA regional screening levels (RSL) database, so that users can input in an analyte and get back a small graph with residential and industrial screening levels for that particular analyte. Here is an example of that data: [ ](https://semspub.epa.gov/work/HQ/402369.pdf). The data is also available in Excel. Hopefully that is something we can get to work with Eleventy.

**Comment by ghost** [comment]
Let's do yours third sprint, that will give us a bit more time to prepare - there are a couple pieces that we need to look into, and so it would be good to have time to pivot, if it turns out we need to change plans a little based on technological/time constraints. This sounds like a cool idea to me. When you have a chance, can you show me a screenshot of what sort of graph you might like, or describe it? I'm not familiar with the context. I'll then look into.

If there's a web API for the "RSL data", we can use that to fetch the data. Otherwise, if that doesn't work out, we can add it to the data folder in some format, and access it in the template for your page.

One more question. What sort of input do you imagine for the user to get the "particular analyte" data to display as a graph?

Here are a couple possible options.

(a) user selects from radio options (think list of options that you fill in circle for one, and only one), and hits a button to display the graph.
(b) user types the name of what they want into an input box (think form field when you sign up for stuff, like "first name"). Then click a button to retrieve the data and graph it.

**Comment by ghost** [comment]
ooo, I just casually Googled this. This might just do the job: 

a `perspective note`:  If you ever work with another SSG, you can try to do some graph stuff there. And then you'll be able to compare how those technologies are with respect to this kind of task/activity. For example, if you have to do lots of graph stuff, and you have a choice, you probably want graphs to not be hard, and so you might prefer one SSG over another, for this reason.   

`install instructions`: https://www.npmjs.com/package/eleventy-charts
`raw markdown graph implementations`: https://raw.githubusercontent.com/idris-maps/eleventy-charts/master/examples.md
`some of the examples rendered in browser`: http://eleventy-charts.surge.sh/

**Comment by cmneal26** [comment]
Wow I love that chart feature! I don't know if it will work with the kind of data I thinking of though. An output that would be easier to read would be more like a table with four rows and two columns, kind of like the table in my project last quarter.

It's annoying that links seem to disappear when I post them, but the analyte data would probably be best as a type-in feature (b). A list would be so long that the viewer might get disinterested. We could specify that it is not case sensitive.

**Comment by ghost** [comment]
Can you supply a screenshot of the table of one analyte from your project? If what you want is a table and not a chart, then it might be easiest to just use a native HTML <table> element. I'm going to provide a starter and merge it for you to experiment with. You don't have to use this in the end, and we might have to tweak it. But it should give you a basic place to experiment with the pieces of the functionality needed. This would be the fallback option to use if we can't find an api for your data (if you know if an api, let me know pls. if it's not public, that's okay too).

`clarification note`: feel free to change the starter files I provided for this fallback option however you want.

 I'll link the PR once I open it here. I'm going to merge it, so it's a little easier to approach.

**Comment by ghost** [comment]
Here is the code PR added to get that create table from data folder almost working. backup plan for no api. I merged it.

- https://github.com/cmneal26/Tech-Writing-Project/pull/67/files
- this is a first pass, and the visual stuff is in place but not quite the strategy to get the data into the html table using javascript.
- once the strategy is ironed out and implemented, when you click retrieve, an HTML <table> table for the analyte retrieved via the search box will be displayed on the page."
- click clear analyte to clear the generated table

**Comment by ghost** [comment]
@self

We might need another backup plan, depending on how this data injection into the inline script thing works out. 

Final fallback that I know will work: we basically build the table first for each analyte retrieved, and then hide it with html. Can use templating language for this. Maybe figure out how to have a partial, not sure. Will look into it later, we still have a lot of time for this one.

**Comment by ghost** [comment]
@cmneal26 if you can, try to find an RLS analyte API to retrieve this data. That would be the best case scenario. But we're fine if it's not available

**Comment by ghost** [comment]
@cmneal26 okay, we won't use the api, so you don't need to find one. this is an opportunity to practice what looks to be a very valuable Eleventy coding pattern.

starter code here: https://github.com/cmneal26/Tech-Writing-Project/pull/79

**Comment by ghost** [comment]
<img width="1779" alt="Screen Shot 2022-07-09 at 4 29 08 PM" src="https://user-images.githubusercontent.com/32662279/178125771-f5ab9693-2664-49f8-8377-fad8edcfbcbc.png">

**Comment by ghost** [comment]
oops, gotta inject substring into id for rows, so no duplicate ids

**Comment by ghost** [comment]
The pattern:

1. put arbitrary data in `_data folder` in  `.js file`
2. iterate through data array/collection, using template language
3. do content stuff, like lists, paragraphs etc. where more than one similar item
4. inject some data to tag items with identifiers.
4. use simple inline javascript to manipulate css classes.
5. for example, although we have five tables on the screen, only one is shown at a time.
4. So, four with class "hide", one with class "show".
5. We're not actually creating one table and destroying another. Just hiding four, and showing one.

javascript -> manipulate css classes when button clicks -> mimic behavior of creating or destroying a table on view
