### ISSUE TITLE
Learning: Comment On A Pull Request

### ISSUE THREAD

**Issue by ghost** [cmneal26/Tech-Writing-Project#4]
Leave a comment on a pull request.

here's a pull request url: https://github.com/cmneal26/Tech-Writing-Project/pull/3

**Comment by ghost** [comment]
I commented on the issue that informs you about a pull request you can comment on.

**Comment by cmneal26** [comment]
I commented on a pull request here:[ ](https://github.com/cmneal26/Tech-Writing-Project/pull/3)

**Comment by twalker** [comment]
Am I mistaken, or were we going to meet via Zoom tonight?
Is there a join link?

**Comment by ghost** [comment]
yeah, we're in the channel. Sorry, updated the meeting forum post, but prob would have been better to post here or email.

**Comment by ghost** [comment]
1.  Go to the course Canvas homepage at https://canvas.uw.edu/courses/1557870

2. Select the "Zoom" tab on the left to transition to the list meetings page.

3.  Join the top meeting that is labeled "Tue, Jun 28 (Recurring)"
