### ISSUE TITLE
Add function selectRandomOpponent(opponents) to the inline javascript on the 'Kids' 

### ISSUE THREAD

**Issue by ghost** [cmneal26/Tech-Writing-Project#47]
Since each game will have a new and random opponent from an array of Opponent objects, we need a function that will select a random opponent.

calling the function with some `input`: `selectRandomOpponents([{name: "Nighteyes"}, {name: "Simba"}])` 
// const randomValue = 1 // selectRandomOpponents()[1] == Simba

return value (output): Simba

conclusion: opponent - Simba

**Comment by ghost** [comment]
You you got this one, Claire.

**Comment by cmneal26** [comment]
I'll work on it tonight!

**Comment by ghost** [comment]
No hurry, whenever you have time. If you're not sure where to place it, we can talk about it in that 10 min or whatever period tomorrow (tuesday) where we catch up.
